#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function evaluateAgentJSON(llmJsonPath, truthPath) {
    let llmResponse, truth;
    try {
        llmResponse = JSON.parse(fs.readFileSync(llmJsonPath, 'utf-8'));
        truth = JSON.parse(fs.readFileSync(truthPath, 'utf-8'));
    } catch (e) {
        return { score: 0.0, error: 'Failed to load JSON files: ' + e.message };
    }

    const expectedMap = {};
    for (const item of truth.expected_outputs) {
        expectedMap[item.test_id] = item.output;
    }

    if (!Array.isArray(llmResponse)) {
        return { score: 0.0, error: 'LLM Response must be a JSON array.' };
    }

    if (llmResponse.length !== truth.expected_outputs.length) {
        return { score: 0.0, error: `LLM Response array length (${llmResponse.length}) does not match expected (${truth.expected_outputs.length}).` };
    }

    let passed = 0;
    const failedTests = [];

    for (const item of llmResponse) {
        const expected = expectedMap[item.test_id];
        if (expected === undefined) {
            return { score: 0.0, error: `Invalid test_id in LLM response: ${item.test_id}` };
        }

        if (item.output === expected) {
            passed++;
        } else {
            failedTests.push({
                test_id: item.test_id,
                expected: expected,
                got: item.output
            });
        }
    }

    const score = passed === truth.expected_outputs.length ? 1.0 : 0.0;
    
    return {
        score: score,
        passed: passed,
        total: truth.expected_outputs.length,
        error: passed === truth.expected_outputs.length ? null : "One or more test cases failed.",
        failed_examples: failedTests.slice(0, 3) 
    };
}

function printUsage() {
    console.log(`
Usage: evaluate_cli.js <llm_output_json> [ground_truth_json]

Arguments:
  llm_output_json    Path to the JSON file generated by the LLM
  ground_truth_json  (Optional) Path to the ground truth JSON. Defaults to ground_truth.json

Example:
  ./evaluate_cli.js llm_output.json
    `);
}

const args = process.argv.slice(2);

if (args.length === 0 || args[0] === '-h' || args[0] === '--help') {
    printUsage();
    process.exit(0);
}

const llmOutputPath = path.resolve(args[0]);
let truthPath = path.resolve(path.join(__dirname, 'ground_truth.json'));

if (args.length > 1) {
    truthPath = path.resolve(args[1]);
}

if (!fs.existsSync(llmOutputPath)) {
    console.error(`Error: LLM output file not found at ${llmOutputPath}`);
    process.exit(1);
}

if (!fs.existsSync(truthPath)) {
    console.error(`Error: Ground truth file not found at ${truthPath}`);
    process.exit(1);
}

console.log(`Evaluating LLM Output: ${llmOutputPath}`);
console.log(`Against Ground Truth:  ${truthPath}`);
console.log('----------------------------------------------------');

const result = evaluateAgentJSON(llmOutputPath, truthPath);

if (result.score === 1.0) {
    console.log(`✅ SUCCESS! Score: 1.0 (${result.passed}/${result.total} passed)`);
} else {
    const passed = result.passed || 0;
    const total = result.total || 0;
    console.log(`❌ FAILED! Score: 0.0 (${passed}/${total} passed)`);
    if (result.error) {
        console.log(`\nError Details:\n  ${result.error}`);
    }
    if (result.failed_examples && result.failed_examples.length > 0) {
        console.log('\nFailed Examples (showing up to 3):');
        result.failed_examples.forEach((ex, idx) => {
            console.log(`  [${idx + 1}] Test ID: ${ex.test_id}`);
            console.log(`      Expected: ${ex.expected}`);
            console.log(`      Got:      ${ex.got}`);
        });
    }
}
